affy-probeset-ids-belns(version, createdDateTime) ::= <<
[Namespace]
NameString=Affymetrix Probe Set Identifiers
Keyword=AFFX
DomainString=Gene and Gene Products
SpeciesString=9606, 10090, 10116
DescriptionString=Affymetrix probe set identfiers for 3' IVT expression analysis arrays (HG U133 Plus 2.0, HG U133 Set, HG U95Av2, HG U219, MG 430 2.0, MG 430A 2.0, MG 430 Set, MG U74 Set, RG 230 2.0, RG 230 Set, HT_HG-U133_Plus_PM, HT_MG-430A, HT_Rat230_PM). These identifiers may be used to specify RNA abundance.
VersionString=<version>
CreatedDateTime=<createdDateTime>

[Author]
NameString=OpenBEL
CopyrightString=Copyright (c) 2015, OpenBEL Project. This work is licensed under a Creative Commons Attribution 3.0 Unported License.
ContactInfoString=info@openbel.org

[Citation]
NameString=Affymetrix, Santa Clara, California, USA
DescriptionString=Affymetrix probe set identfiers for 3' IVT expression analysis arrays.
PublishedVersionString=na35
PublishedDate=2015-04-16
ReferenceURL=http://www.affymetrix.com/analysis

[Processing]
CaseSensitiveFlag=yes
DelimiterString=|
CacheableFlag=yes

[Values]

>>
