cell-ontology-belanno(version, createdDateTime, uri) ::= <<
[AnnotationDefinition]
Keyword=Cell
TypeString=list
DescriptionString=Cell types from the Cell Ontology (CL)
UsageString=Use this annotation to indicate the cell type context of a statement. Use to annotate a statement that was demonstrated in a given cell type or where the facts represented in the statement were shown to be relevant to the cell type.
VersionString=<version>
CreatedDateTime=<createdDateTime>
URIString=<uri>

[Author]
NameString=OpenBEL
CopyrightString=Copyright (c) 2015, OpenBEL Project. This work is licensed under a Creative Commons Attribution 3.0 Unported License.
ContactInfoString=info@openbel.org

[Citation]
NameString=Cell Ontology (CL)
DescriptionString=The Cell Ontology (CL) is a candidate OBO Foundry ontology for the representation of cell types. First described in 2005, the CL integrates cell types from the prokaryotic, fungal, and eukaryotic organisms.
PublishedVersionString=http://purl.obolibrary.org/obo/cl/releases/2015-05-12/cl.owl
PublishedDate=2015-05-12
ReferenceURL=http://cellontology.org/

[Processing]
CaseSensitiveFlag=yes
DelimiterString=|
CacheableFlag=yes

[Values]

>>
