chebi-ids-belns(version, createdDateTime) ::= <<
[Namespace]
NameString=Chemicals of Biological Interest (Identifiers)
Keyword=CHEBIID
DomainString=Chemical
SpeciesString=all
DescriptionString=Chemical Entities of Biological Interest (ChEBI) unique identifiers. These identifiers may be used to specify abundances.
VersionString=<version>
CreatedDateTime=<createdDateTime>
QueryValueURL=http://www.ebi.ac.uk/chebi/searchId.do?chebiId=[VALUE]

[Author]
NameString=OpenBEL
CopyrightString=Copyright (c) 2015, OpenBEL Project. This work is licensed under a Creative Commons Attribution 3.0 Unported License.
ContactInfoString=info@openbel.org

[Citation]
NameString=ChEBI
DescriptionString=Chemical Entities of Biological Interest (ChEBI) is a freely available dictionary of molecular entities focused on .small. chemical compounds.
PublishedVersionString=127
PublishedDate=2015-06-01
ReferenceURL=http://www.ebi.ac.uk/chebi/

[Processing]
CaseSensitiveFlag=yes
DelimiterString=|
CacheableFlag=yes

[Values]

>>
