chebi-ids-beleq(version, createdDateTime) ::= <<
[Equivalence]
NameString=Chemicals of Biological Interest (Names) Equivalences
DescriptionString=ChEBI Identifier equivalences. Chemical and small molecule namespace equivalences are rooted to ChEBI, such that each primary ChEBI identifier is assigned a unique UUID.
VersionString=<version>
CreatedDateTime=<createdDateTime>

[NamespaceReference]
NameString=Chemicals of Biological Interest (Names)
VersionString=<version>

[Author]
NameString=OpenBEL
CopyrightString=Copyright (c) 2015, OpenBEL Project. This work is licensed under a Creative Commons Attribution 3.0 Unported License.
ContactInfoString=info@openbel.org

[Citation]
NameString=ChEBI
DescriptionString=chebi.owl file
PublishedVersionString=127
PublishedDate=2015-06-01
ReferenceURL=http://www.ebi.ac.uk/chebi/

[Processing]
CaseSensistiveFlag=yes
DelimiterString=|
CacheableFlag=yes

[Values]

>>
