chebi-beleq(version, createdDateTime) ::= <<
[Equivalence]
NameString=Chemicals of Biological Interest (Identifiers) Equivalences
DescriptionString=ChEBI Name equivalences are assigned based on the correpsonding ChEBI identifier. 
VersionString=<version>
CreatedDateTime=<createdDateTime>

[NamespaceReference]
NameString=Chemicals of Biological Interest (Identifiers)
VersionString=<version>

[Author]
NameString=OpenBEL
CopyrightString=Copyright (c) 2015, OpenBEL Project. This work is licensed under a Creative Commons Attribution 3.0 Unported License.
ContactInfoString=info@openbel.org

[Citation]
NameString=ChEBI
DescriptionString=chebi.owl file
PublishedVersionString=127
PublishedDate=2015-06-01
ReferenceURL=http://www.ebi.ac.uk/chebi/

[Processing]
CaseSensistiveFlag=yes
DelimiterString=|
CacheableFlag=yes

[Values]

>>
