chembl-ids-beleq(version, createdDateTime) ::= <<
[Equivalence]
NameString=ChEMBL
DescriptionString=ChEMBL is a manually curated chemical database of bioactive molecules with drug-like properties
VersionString=<version>
CreatedDateTime=<createdDateTime>

[NamespaceReference]
NameString=ChEMBL
VersionString=<version>

[Author]
NameString=OpenBEL
CopyrightString=Copyright (c) 2015, OpenBEL Project. This work is licensed under a Creative Commons Attribution 3.0 Unported License.
ContactInfoString=info@openbel.org

[Citation]
NameString=ChEMBL
DescriptionString=ChEMBL is a manually curated chemical database of bioactive molecules with drug-like properties
PublishedVersionString=2015-11-13
PublishedDate=2015-11-13
ReferenceURL=https://www.ebi.ac.uk/chembl/

[Processing]
CaseSensistiveFlag=yes
DelimiterString=|
CacheableFlag=yes

[Values]

>>
