default-bel-namespace-beleq(version, createdDateTime) ::= <<
[Equivalence]
NameString=Default BEL namespace equivalences
DescriptionString=Equivalences used by the default BEL namespace.
VersionString=<version>
CreatedDateTime=<createdDateTime>

[NamespaceReference]
NameString=Default BEL Namespace
VersionString=<version>

[Author]
NameString=OpenBEL
CopyrightString=Copyright (c) 2016, OpenBEL Project. This work is licensed under a Creative Commons Attribution 3.0 Unported License.
ContactInfoString=info@openbel.org

[Citation]
NameString=N/A
DescriptionString=N/A

[Processing]
CaseSensistiveFlag=yes
DelimiterString=|
CacheableFlag=yes

[Values]

>>
