default-bel-namespace-belns(version, createdDateTime, uri) ::= <<
[Namespace]
NameString=Default BEL Namespace
Keyword=DEFAULT
DomainString=Any
SpeciesString=all
DescriptionString=The BEL default namespace.
VersionString=<version>
CreatedDateTime=<createdDateTime>
URIString=<uri>

[Author]
NameString=OpenBEL
CopyrightString=Copyright (c) 2016, OpenBEL Project. This work is licensed under a Creative Commons Attribution 3.0 Unported License.
ContactInfoString=info@openbel.org

[Citation]
NameString=Selventa
DescriptionString=The BEL default namespace.
PublishedVersionString=Version2
PublishedDate=2016-05-23

[Processing]
CaseSensitiveFlag=yes
DelimiterString=|
CacheableFlag=yes

[Values]

>>
