disease-ontology-belanno(version, createdDateTime, uri) ::= <<
[AnnotationDefinition]
Keyword=Disease
TypeString=list
DescriptionString=Disease names from the Disease Ontology (DO)
UsageString=Use to annotate a statement demonstrated in a biological system where the disease state was present or where the facts represented in the statement were shown to be relevant to the disease.
VersionString=<version>
CreatedDateTime=<createdDateTime>
URIString=<uri>

[Author]
NameString=OpenBEL
CopyrightString=Copyright (c) 2015, OpenBEL Project. This work is licensed under a Creative Commons Attribution 3.0 Unported License.
ContactInfoString=info@openbel.org

[Citation]
NameString=Disease Ontology (DO)
DescriptionString=The Disease Ontology has been developed as a standardized ontology for human disease with the purpose of providing the biomedical community with consistent, reusable and sustainable descriptions of human disease terms, phenotype characteristics and related medical vocabulary disease concepts through collaborative efforts of researchers at Northwestern University, Center for Genetic Medicine and the University of Maryland School of Medicine, Institute for Genome Sciences. The Disease Ontology semantically integrates disease and medical vocabularies through extensive cross mapping of DO terms to MeSH, ICD, NCI's thesaurus, SNOMED and OMIM.
PublishedVersionString=http://purl.obolibrary.org/obo/doid/releases/2015-06-04/doid.owl
PublishedDate=2015-06-04
ReferenceURL=http://disease-ontology.org/

[Processing]
CaseSensitiveFlag=yes
DelimiterString=|
CacheableFlag=yes

[Values]

>>
