disease-ontology-ids-beleq(version, createdDateTime) ::= <<
[Equivalence]
NameString=Disease Ontology Identifier Equivalences
DescriptionString=Disease Ontology identifier equivalences. Disease namespace equivalences are rooted to Disease Ontology identifiers, such that each Disease Ontology identifier is assigned a unique UUID.
VersionString=<version>
CreatedDateTime=<createdDateTime>

[NamespaceReference]
NameString=Disease Ontology Idenitifers
VersionString=<version>

[Author]
NameString=OpenBEL
CopyrightString=Copyright (c) 2015, OpenBEL Project. This work is licensed under a Creative Commons Attribution 3.0 Unported License.
ContactInfoString=info@openbel.org

[Citation]
NameString=The Disease Ontology (DO)
DescriptionString=The Disease Ontology OWL file, http://www.berkeleybop.org/ontologies/doid.owl
PublishedVersionString=2015-06-11
PublishedDate=2015-06-11
ReferenceURL=http://disease-ontology.org/

[Processing]
CaseSensistiveFlag=yes
DelimiterString=|
CacheableFlag=yes

[Values]

>>
