entrez-gene-ids-beleq(version, createdDateTime) ::= <<
[Equivalence]
NameString=Entrez Gene Identifier Equivalences
DescriptionString=Entrez Gene identifier equivalences. Gene and Gene Product namespace equivalences are rooted to Entrez Gene, such that each Entrez Gene identifier is assigned a unique UUID.
VersionString=<version>
CreatedDateTime=<createdDateTime>

[NamespaceReference]
NameString=Entrez Gene Identifiers
VersionString=<version>

[Author]
NameString=OpenBEL
CopyrightString=Copyright (c) 2015, OpenBEL Project. This work is licensed under a Creative Commons Attribution 3.0 Unported License.
ContactInfoString=info@openbel.org

[Citation]
NameString=NCBI Entrez Gene
DescriptionString=NCBI gene_info file.
PublishedVersionString=Thu, 11 Jun 2015 02:58:39
PublishedDate=2015-06-11
ReferenceURL=http://www.ncbi.nlm.nih.gov/gene

[Processing]
CaseSensistiveFlag=yes
DelimiterString=|
CacheableFlag=yes

[Values]

>>
