experimental-factor-ontology-belanno(version, createdDateTime, uri) ::= <<
[AnnotationDefinition]
Keyword=ExperimentalFactorOntology
TypeString=list
DescriptionString=Experimental Factor Ontology (EFO) Cell Lines
UsageString=Use this annotation to indicate the cell line context of a statement. Use to annotate a statement that was demonstrated in a given cell line.
VersionString=<version>
CreatedDateTime=<createdDateTime>
URIString=<uri>

[Author]
NameString=OpenBEL
CopyrightString=Copyright (c) 2015, OpenBEL Project. This work is licensed under a Creative Commons Attribution 3.0 Unported License.
ContactInfoString=info@openbel.org

[Citation]
NameString=Experimental Factor Ontology (EFO)
DescriptionString=The Experimental Factor Ontology (EFO) provides a systematic description of many experimental variables available in EBI databases.
PublishedVersionString=2.60
PublishedDate=2015-05-15
ReferenceURL=http://www.ebi.ac.uk/efo/

[Processing]
CaseSensitiveFlag=yes
DelimiterString=|
CacheableFlag=yes

[Values]

>>
