go-biological-process-ids-beleq(version, createdDateTime) ::= <<
[Equivalence]
NameString=GO Biological Process Identifier Equivalences
DescriptionString=GO Biological Process Identifier equivalences. Biological Process namespace equivalences are rooted to GO, such that each primary GO Biological Process identifier is assigned a unique UUID.
VersionString=<version>
CreatedDateTime=<createdDateTime>

[NamespaceReference]
NameString=GO Biological Process Identifiers
VersionString=<version>

[Author]
NameString=OpenBEL
CopyrightString=Copyright (c) 2015, OpenBEL Project. This work is licensed under a Creative Commons Attribution 3.0 Unported License.
ContactInfoString=info@openbel.org

[Citation]
NameString=The Gene Ontology Consortium
DescriptionString=GO obo-xml file.
PublishedVersionString=2015-05-30
PublishedDate=2015-05-29
ReferenceURL=http://www.geneontology.org/

[Processing]
CaseSensistiveFlag=yes
DelimiterString=|
CacheableFlag=yes

[Values]

>>
