go-biological-process-ids-belns(version, createdDateTime, uri) ::= <<
[Namespace]
NameString=GO Biological Process Identifiers
Keyword=GOBPID
DomainString=Biological Process
SpeciesString=all
DescriptionString=The Gene Ontology (GO) identifiers for biological process. These IDs may be used to represent biological processes.
VersionString=<version>
CreatedDateTime=<createdDateTime>
URIString=<uri>
QueryValueURL=http://amigo.geneontology.org/cgi-bin/amigo/term_details?term=GO:[VALUE]

[Author]
NameString=OpenBEL
CopyrightString=Copyright (c) 2015, OpenBEL Project. This work is licensed under a Creative Commons Attribution 3.0 Unported License.
ContactInfoString=info@openbel.org

[Citation]
NameString=The Gene Ontology Consortium
DescriptionString=The Gene Ontology project is a major bioinformatics initiative with the aim of standardizing the representation of gene and gene product attributes across species and databases.
PublishedVersionString=2015-05-30
PublishedDate=2015-05-29
ReferenceURL=http://www.geneontology.org/

[Processing]
CaseSensitiveFlag=yes
DelimiterString=|
CacheableFlag=yes

[Values]

>>
