go-cellular-component-belns(version, createdDateTime) ::= <<
[Namespace]
NameString=GO Cellular Components (Names)
Keyword=GOCC
DomainString=Cell Components and Complexes
SpeciesString=all
DescriptionString=Gene Ontology (GO) cellular component names. These terms may be used to represent cellular components as well as complex abundances.
VersionString=<version>
CreatedDateTime=<createdDateTime>
QueryValueURL=http://amigo.geneontology.org/cgi-bin/amigo/search.cgi?search_query=[VALUE]&search_constraint=term&exact_match=1&action=new-search

[Author]
NameString=OpenBEL
CopyrightString=Copyright (c) 2015, OpenBEL Project. This work is licensed under a Creative Commons Attribution 3.0 Unported License.
ContactInfoString=info@openbel.org

[Citation]
NameString=The Gene Ontology Consortium
DescriptionString=The Gene Ontology project is a major bioinformatics initiative with the aim of standardizing the representation of gene and gene product attributes across species and databases.
PublishedVersionString=2015-05-30
PublishedDate=2015-05-29
ReferenceURL=http://www.geneontology.org

[Processing]
CaseSensitiveFlag=yes
DelimiterString=|
CacheableFlag=yes

[Values]
