hgnc-human-genes-belns(version, createdDateTime, uri) ::= <<
[Namespace]
NameString=HGNC Approved Gene Symbols
Keyword=HGNC
DomainString=Gene and Gene Products
SpeciesString=9606
DescriptionString=HUGO Gene Nomenclature Committee (HGNC) approved gene symbols. These symbols may be used to specify human gene, RNA, microRNA and protein abundances. Single character encoding following each value specify which abundance types are valid.
VersionString=<version>
CreatedDateTime=<createdDateTime>
URIString=<uri>
QueryValueURL=http://www.genenames.org/data/hgnc_data.php?match=[VALUE]

[Author]
NameString=OpenBEL
CopyrightString=Copyright (c) 2015, OpenBEL Project. This work is licensed under a Creative Commons Attribution 3.0 Unported License.
ContactInfoString=info@openbel.org

[Citation]
NameString=HUGO Gene Nomenclature Committee at the European Bioinformatics Institute
DescriptionString=The HGNC approved gene symbols for human. Each symbol is unique and each gene is only given one approved gene symbol.
PublishedVersionString=Thu, 11 Jun 2015 06:00:09
PublishedDate=2015-06-11
ReferenceURL=http://www.genenames.org/

[Processing]
CaseSensitiveFlag=yes
DelimiterString=|
CacheableFlag=yes

[Values]

>>
