mesh-cellular-structures-beleq(version, createdDateTime) ::= <<
[Equivalence]
NameString=MeSH Cellular Location (Name) Equivalences
DescriptionString=MeSH  equivalences were obtained by string match of MeSH headings and synonyms to GO Cellular Component names.
VersionString=<version>
CreatedDateTime=<createdDateTime>

[NamespaceReference]
NameString=MeSH Cellular Locations (Names)
VersionString=<version>

[Author]
NameString=OpenBEL
CopyrightString=Copyright (c) 2015, OpenBEL Project. This work is licensed under a Creative Commons Attribution 3.0 Unported License.
ContactInfoString=info@openbel.org

[Citation]
NameString=N/A
DescriptionString=N/A

[Processing]
CaseSensistiveFlag=yes
DelimiterString=|
CacheableFlag=yes

[Values]

>>
