mesh-cellular-structures-belanno(version, createdDateTime) ::= <<
[AnnotationDefinition]
Keyword=CellStructure
TypeString=list
DescriptionString=The Cell Structures [A11.284] sub-branch of the Medical Subject Headings (MeSH) Anatomy [A] branch.
UsageString=Use to annotate a statement demonstrated in the context of a specific cellular location.
VersionString=<version>
CreatedDateTime=<createdDateTime>

[Author]
NameString=OpenBEL
CopyrightString=Copyright (c) 2015, OpenBEL Project. This work is licensed under a Creative Commons Attribution 3.0 Unported License.
ContactInfoString=info@openbel.org

[Citation]
NameString=MeSH
DescriptionString=MeSH (Medical Subject Headings) is a controlled vocabulary thesaurus created, maintained, and provided by the U.S. National Library of Medicine.
PublishedVersionString=2015
ReferenceURL=http://www.nlm.nih.gov/mesh/meshhome.html

[Processing]
CaseSensitiveFlag=yes
DelimiterString=|
CacheableFlag=yes

[Values]

>>
