mesh-processes-ids-belns(version, createdDateTime, uri) ::= <<
[Namespace]
NameString=MeSH Phenomena and Processes (Identifiers)
Keyword=MESHPPID
DomainString=Biological Process
SpeciesString=all
DescriptionString=Medical Subject Headings (MeSH) from the Phenomena and Processes [G] branch, excluding the [G01], [G15], and [G17] sub-branches. These headings may be used to specify biological processes.
VersionString=<version>
CreatedDateTime=<createdDateTime>
URIString=<uri>
QueryValueURL=http://www.nlm.nih.gov/cgi/mesh/2013/MB_cgi?mode=&term=[VALUE]&field=entry

[Author]
NameString=OpenBEL
CopyrightString=Copyright (c) 2015, OpenBEL Project. This work is licensed under a Creative Commons Attribution 3.0 Unported License.
ContactInfoString=info@openbel.org

[Citation]
NameString=MeSH
DescriptionString=MeSH (Medical Subject Headings) is a controlled vocabulary thesaurus created, maintained, and provided by the U.S. National Library of Medicine.
PublishedVersionString=2015
PublishedDate=2015-06-11
ReferenceURL=http://www.nlm.nih.gov/mesh/meshhome.html

[Processing]
CaseSensitiveFlag=yes
DelimiterString=|
CacheableFlag=yes

[Values]

>>
