mesh-anatomy-belanno(version, createdDateTime) ::= <<
[AnnotationDefinition]
Keyword=MeSHAnatomy
TypeString=list
DescriptionString=Anatomy terms from Medical Subject Headings (MeSH), limited to headings from the following subbranches:[A01], [A02], [A03], [A04], [A05], [A06], [A07], [A08], [A09], [A10], [A12], [A14], [A15], [A16], and [A17].
UsageString=Use to annotate a statement demonstrated in a specific anatomical entity.
VersionString=<version>
CreatedDateTime=<createdDateTime>

[Author]
NameString=OpenBEL
CopyrightString=Copyright (c) 2015, OpenBEL Project. This work is licensed under a Creative Commons Attribution 3.0 Unported License.
ContactInfoString=info@openbel.org

[Citation]
NameString=MeSH
DescriptionString=MeSH (Medical Subject Headings) is a controlled vocabulary thesaurus created, maintained, and provided by the U.S. National Library of Medicine.
PublishedVersionString=2015
ReferenceURL=http://www.nlm.nih.gov/mesh/meshhome.html

[Processing]
CaseSensitiveFlag=yes
DelimiterString=|
CacheableFlag=yes

[Values]

>>
