mesh-cellular-structures-ids-belns(version, createdDateTime) ::= <<
[Namespace]
NameString=MeSH Cellular Structures (Identifiers)
Keyword=MESHCSID
DomainString=Cell Components and Complexes
SpeciesString=all
DescriptionString=Medical Subject Headings (MeSH) names for cellular locations [branch A11.284].
VersionString=<version>
CreatedDateTime=<createdDateTime>
QueryValueURL=http://www.nlm.nih.gov/cgi/mesh/2013/MB_cgi?mode=&term=[VALUE]&field=entry

[Author]
NameString=OpenBEL
CopyrightString=Copyright (c) 2015, OpenBEL Project. This work is licensed under a Creative Commons Attribution 3.0 Unported License.
ContactInfoString=info@openbel.org

[Citation]
NameString=MeSH
DescriptionString=MeSH (Medical Subject Headings) is a controlled vocabulary thesaurus created, maintained, and provided by the U.S. National Library of Medicine.
PublishedVersionString=2015
PublishedDate=2015-06-11
ReferenceURL=http://www.nlm.nih.gov/mesh/meshhome.html

[Processing]
CaseSensitiveFlag=yes
DelimiterString=|
CacheableFlag=yes

[Values]
