mesh-diseases-beleq(version, createdDateTime) ::= <<
[Equivalence]
NameString=MeSH Diseases Heading Equivalences
DescriptionString=MeSH Disease Headings equivalences were obtained from the Disease Ontology cross-references to MeSH.
VersionString=<version>
CreatedDateTime=<createdDateTime>

[NamespaceReference]
NameString=MeSH Diseases Headings
VersionString=<version>

[Author]
NameString=OpenBEL
CopyrightString=Copyright (c) 2015, OpenBEL Project. This work is licensed under a Creative Commons Attribution 3.0 Unported License.
ContactInfoString=info@openbel.org

[Citation]
NameString=The Disease Ontology
DescriptionString=The Disease Ontology cross references to MeSH. 
PublishedVersionString=2015-06-11
PublishedDate=2015-06-11
ReferenceURL=http://disease-ontology.org/

[Processing]
CaseSensistiveFlag=yes
DelimiterString=|
CacheableFlag=yes

[Values]

>>
