mesh-diseases-belanno(version, createdDateTime, uri) ::= <<
[AnnotationDefinition]
Keyword=MeSHDisease
TypeString=list
DescriptionString=Disease terms from the [C] branch of Medical Subject Headings (MeSH).
UsageString=Use to annotate a statement demonstrated in the context of a specific disease.
VersionString=<version>
CreatedDateTime=<createdDateTime>
URIString=<uri>

[Author]
NameString=OpenBEL
CopyrightString=Copyright (c) 2015, OpenBEL Project. This work is licensed under a Creative Commons Attribution 3.0 Unported License.
ContactInfoString=info@openbel.org

[Citation]
NameString=MeSH
DescriptionString=MeSH (Medical Subject Headings) is a controlled vocabulary thesaurus created, maintained, and provided by the U.S. National Library of Medicine.
PublishedVersionString=2015
ReferenceURL=http://www.nlm.nih.gov/mesh/meshhome.html

[Processing]
CaseSensitiveFlag=yes
DelimiterString=|
CacheableFlag=yes

[Values]

>>
