mgi-mouse-genes-beleq(version, createdDateTime) ::= <<
[Equivalence]
NameString=MGI Symbol Equivalences
DescriptionString=MGI symbol equivalences based on the Entrez Gene gene_info file. MGI Symbols without an associated Entrez GeneID are assigned a new UUID.
VersionString=<version>
CreatedDateTime=<createdDateTime>

[NamespaceReference]
NameString=MGI Approved Gene Symbols
VersionString=<version>

[Author]
NameString=OpenBEL
CopyrightString=Copyright (c) 2015, OpenBEL Project. This work is licensed under a Creative Commons Attribution 3.0 Unported License.
ContactInfoString=info@openbel.org

[Citation]
NameString=NCBI Entrez Gene
DescriptionString=NCBI gene_info file.
PublishedVersionString=Thu, 11 Jun 2015 02:58:39
PublishedDate=2015-06-11
ReferenceURL=http://www.ncbi.nlm.nih.gov/gene

[Processing]
CaseSensistiveFlag=yes
DelimiterString=|
CacheableFlag=yes

[Values]

>>
