ncbi-taxonomy-belanno(version, createdDateTime) ::= <<
[AnnotationDefinition]
Keyword=Species
TypeString=list
DescriptionString=The annotation values for species provided by NCBI Taxonomy Identifiers.
UsageString=Use this annotation to indicate the species context for a statement.
VersionString=<version>
CreatedDateTime=<createdDateTime>

[Author]
NameString=OpenBEL
CopyrightString=OpenBEL (c) 2013, OpenBEL Project. This work is licensed under a Creative Commons Attribution 3.0 Unported License.
ContactInfoString=belframework@selventa.com

[Citation]
NameString=NCBI Taxonomy Ids
DescriptionString=NCBI maintains species taxonomies
PublishedVersionString=20120202
PublishedDate=2011-02-02
ReferenceURL=http://www.ncbi.nlm.nih.gov/Taxonomy/taxonomyhome.html/

[Processing]
CaseSensitiveFlag=no
DelimiterString=|
CacheableFlag=yes

[Values]

>>
