rgd-rat-genes-belns(version, createdDateTime, uri) ::= <<
[Namespace]
NameString=RGD Approved Gene Symbols
Keyword=RGD
DomainString=Gene and Gene Products
SpeciesString=10116
DescriptionString=Rat Genome Database (RGD) approved gene symbols. These symbols may be used to specify rat gene, RNA, microRNA and protein abundances. Single character encoding following each value specify which abundance types are valid.
VersionString=<version>
CreatedDateTime=<createdDateTime>
URIString=<uri>
QueryValueURL=http://rgd.mcw.edu/rgdweb/search/genes.html?term=[VALUE]&speciesType=3

[Author]
NameString=OpenBEL
CopyrightString=Copyright (c) 2015, OpenBEL Project. This work is licensed under a Creative Commons Attribution 3.0 Unported License.
ContactInfoString=info@openbel.org

[Citation]
NameString=Rat Genome Database Web Site, Medical College of Wisconsin, Milwaukee, Wisconsin.
DescriptionString=The Rat Genome Database (RGD) approved gene symbols for Rat.
PublishedVersionString=2015-06-05
PublishedDate=2015-06-05
ReferenceURL=http://rgd.mcw.edu/

[Processing]
CaseSensitiveFlag=yes
DelimiterString=|
CacheableFlag=yes

[Values]

>>
