selventa-legacy-diseases-beleq(version, createdDateTime) ::= <<
[Equivalence]
NameString=Selventa Legacy Disease Name Equivalences
DescriptionString=Selventa Legacy Disease Name equivalences were assigned based on string match to Disease Ontology names. 
VersionString=<version>
CreatedDateTime=<createdDateTime>

[NamespaceReference]
NameString=Selventa Legacy Disease Names
VersionString=<version>

[Author]
NameString=OpenBEL
CopyrightString=Copyright (c) 2015, OpenBEL Project. This work is licensed under a Creative Commons Attribution 3.0 Unported License.
ContactInfoString=info@openbel.org

[Citation]
NameString=N/A
DescriptionString=N/A

[Processing]
CaseSensistiveFlag=yes
DelimiterString=|
CacheableFlag=yes

[Values]

>>
