selventa-named-complexes-beleq(version, createdDateTime) ::= <<
[Equivalence]
NameString=iSelventa Named Complexes Equivalence
DescriptionString=Selventa Named Complexes equivalences were assigned based on string match and manual matches to GO Cellular Component complexes.
VersionString=<version>
CreatedDateTime=<createdDateTime>

[NamespaceReference]
NameString=Selventa Named Complexes
VersionString=<version>

[Author]
NameString=OpenBEL
CopyrightString=Copyright (c) 2015, OpenBEL Project. This work is licensed under a Creative Commons Attribution 3.0 Unported License.
ContactInfoString=info@openbel.org

[Citation]
NameString=N/A
DescriptionString=N/A

[Processing]
CaseSensitiveFlag=yes
DelimiterString=|
CacheableFlag=yes

[Values]

>>
