selventa-named-complexes-belns(version, createdDateTime) ::= <<
[Namespace]
Keyword=SCOMP
NameString=Selventa Named Complexes
DomainString=Gene/Protein
SpeciesString=9606, 10090, 10116
DescriptionString=List of named complexes that are frequently used and/or are well characterized such as the NFKB Complex.
VersionString=<version>
CreatedDateTime=<createdDateTime>

[Author]
NameString=Selventa
CopyrightString=Copyright (c) 2015, OpenBEL Project. This work is licensed under a Creative Commons Attribution 3.0 Unported License.
ContactInfoString=info@openbel.org

[Citation]
NameString=Selventa Named Complexes
DescriptionString=Selventa defined names of complexes that are frequently used and/or are well characterized. This Namespace serves to standardize the representation of a complex by providing a standardized name.

[Processing]
CaseSensitiveFlag=yes
DelimiterString=|
CacheableFlag=yes

[Values]

>>
