selventa-legacy-chemicals-belns(version, createdDateTime, uri) ::= <<
[Namespace]
NameString=Selventa Legacy Chemical Names
Keyword=SCHEM
DomainString=Chemical
SpeciesString=all
DescriptionString=Selventa names for chemicals, drugs, and other molecule abundances. It is not recommended that new BEL Documents include reference to any of these legacy namespaces.
VersionString=<version>
CreatedDateTime=<createdDateTime>
URIString=<uri>

[Author]
NameString=OpenBEL
CopyrightString=Copyright (c) 2015, OpenBEL Project. This work is licensed under a Creative Commons Attribution 3.0 Unported License.
ContactInfoString=info@openbel.org

[Citation]
NameString=Selventa
DescriptionString=Selventa names for chemicals, drugs, and other molecule abundances. It is not recommended that new BEL Documents include reference to any of these legacy namespaces.
PublishedVersionString=Tue, 05 May 2015 18:18:57
PublishedDate=2015-05-05

[Processing]
CaseSensitiveFlag=yes
DelimiterString=|
CacheableFlag=yes

[Values]

>>
