selventa-legacy-diseases-belns(version, createdDateTime) ::= <<
[Namespace]
NameString=Selventa Legacy Disease Names
Keyword=SDIS
DomainString=Biological Process
SpeciesString=all
DescriptionString=Selventa legacy names for diseases. It is not recommended that new BEL Documents include reference to any of these legacy namespaces.
VersionString=<version>
CreatedDateTime=<createdDateTime>

[Author]
NameString=OpenBEL
CopyrightString=Copyright (c) 2015, OpenBEL Project. This work is licensed under a Creative Commons Attribution 3.0 Unported License.
ContactInfoString=info@openbel.org

[Citation]
NameString=Selventa
DescriptionString=Selventa legacy names for diseases. It is not recommended that new BEL Documents include reference to any of these legacy namespaces.
PublishedVersionString=Tue, 05 May 2015 18:18:57
PublishedDate=2015-05-05

[Processing]
CaseSensitiveFlag=yes
DelimiterString=|
CacheableFlag=yes

[Values]

>>
