swissprot-beleq(version, createdDateTime) ::= <<
[Equivalence]
NameString=Swiss-Prot Entry Name Equivalences
DescriptionString=Swiss-Prot entry name equivalences to Entrez Gene are assigned based on the database cross references provided by UniProtKB/Swiss-Prot. Entry names that map to no Gene IDs or more than one Gene ID are assigned a new UUID.
VersionString=<version>
CreatedDateTime=<createdDateTime>

[NamespaceReference]
NameString=Swiss-Prot Entry Names
VersionString=<version>

[Author]
NameString=OpenBEL
CopyrightString=Copyright (c) 2015, OpenBEL Project. This work is licensed under a Creative Commons Attribution 3.0 Unported License.
ContactInfoString=info@openbel.org

[Citation]
NameString=Universal Protein Resource (UniProt), UniProt consortium
DescriptionString=Swiss-Prot database cross references to Entrez Gene.
PublishedVersionString=Wed, 27 May 2015 14:00:00
PublishedDate=2015-05-27
ReferenceURL=http://www.uniprot.org

[Processing]
CaseSensistiveFlag=yes
DelimiterString=|
CacheableFlag=yes

[Values]

>>
