swissprot-ids-belns(version, createdDateTime, uri) ::= <<
[Namespace]
NameString=Swiss-Prot Accession Numbers
Keyword=SPID
DomainString=Gene and Gene Products
SpeciesString=9606, 10090, 10116
DescriptionString=Swiss-Prot database accession numbers for Homo sapiens, Mus musculus, and Rattus norvegicus. These may be used to specify gene, RNA and protein abundances. Single character encoding following each value specify which abundance types are valid.
VersionString=<version>
CreatedDateTime=<createdDateTime>
URIString=<uri>
QueryValueURL=http://www.uniprot.org/uniprot/[VALUE]

[Author]
NameString=OpenBEL
CopyrightString=Copyright (c) 2015, OpenBEL Project. This work is licensed under a Creative Commons Attribution 3.0 Unported License.
ContactInfoString=info@openbel.org

[Citation]
NameString=Universal Protein Resource (UniProt), UniProt consortium
DescriptionString=Swiss-Prot is the manually annotated and reviewed section of the UniProt Knowledgebase (UniProtKB). It is a high quality annotated and non-redundant protein sequence database, which brings together experimental results, computed features and scientific conclusions.
PublishedVersionString=Wed, 27 May 2015 14:00:00
PublishedDate=2015-05-27
ReferenceURL=http://www.uniprot.org

[Processing]
CaseSensitiveFlag=yes
DelimiterString=|
CacheableFlag=yes

[Values]

>>
