swissprot-ids-beleq(version, createdDateTime) ::= <<
[Equivalence]
NameString=Swiss-Prot Accession Number Equivalences
DescriptionString=Swiss-Prot accession number equivalences are assigned based on the corresponding Swiss-Prot entry name. 
VersionString=<version>
CreatedDateTime=<createdDateTime>

[NamespaceReference]
NameString=Swiss-Prot Accession Numbers
VersionString=<version>

[Author]
NameString=OpenBEL
CopyrightString=Copyright (c) 2015, OpenBEL Project. This work is licensed under a Creative Commons Attribution 3.0 Unported License.
ContactInfoString=info@openbel.org

[Citation]
NameString=Universal Protein Resource (UniProt), UniProt consortium
DescriptionString=Swiss-Prot database cross references to Entrez Gene.
PublishedVersionString=Wed, 27 May 2015 14:00:00
PublishedDate=2015-05-27
ReferenceURL=http://www.uniprot.org

[Processing]
CaseSensistiveFlag=yes
DelimiterString=|
CacheableFlag=yes

[Values]

>>
