uberon-belanno(version, createdDateTime, uri) ::= <<
[AnnotationDefinition]
Keyword=Uberon
TypeString=list
DescriptionString=Anatomy terms from Uberon
UsageString=Use to annotate a statement demonstrated in a specific anatomical entity.
VersionString=<version>
CreatedDateTime=<createdDateTime>
URIString=<uri>

[Author]
NameString=OpenBEL
CopyrightString=Copyright (c) 2015, OpenBEL Project. This work is licensed under a Creative Commons Attribution 3.0 Unported License.
ContactInfoString=info@openbel.org

[Citation]
NameString=Uberon
DescriptionString=Uberon is an integrated cross-species anatomy ontology representing a variety of entities classified according to traditional anatomical criteria such as structure, function and developmental lineage.
PublishedVersionString=http://purl.obolibrary.org/obo/uberon/releases/2015-05-25/uberon.owl
PublishedDate=2015-05-25
ReferenceURL=http://uberon.org/

[Processing]
CaseSensitiveFlag=yes
DelimiterString=|
CacheableFlag=yes

[Values]

>>
